### ISSUE TITLE
SheetManager.hide('self') stopped working on latest versions

### ISSUE THREAD

**Issue by cospin** [ammarahm-ed/react-native-actions-sheet#263] opened 2023-02-10 08:39 UTC
Hey, thanks again for this excellent work.

I've noticed that in the latest version when calling `SheetManager.hide('self')` nothing happens.
With `self` I mean a registered sheet, which is trying to close itself.

`SheetManager.hideAll()` works fine. Closing from gestures or backdrop works fine too.

I haven't had time to debug this, had to downgrade for now.

**Comment by ammarahm-ed** [comment] 2023-02-11 11:30
I'll take a look.

**Comment by luiscrjunior** [comment] 2023-02-12 14:38
Same problem here.

Downgraded to 0.8.13 and it worked.

Apparently the problem is 0.8.14+.

**Comment by ammarahm-ed** [comment] 2023-02-13 10:26
Fixed in 0.8.19

**Comment by pafry7** [comment] 2023-02-13 10:33
@ammarahm-ed I am not sure if the problem has been fixed. We have to call `hide` twice to close ActionSheet. Is anyone else experiencing this or is it a problem with our code?

**Comment by ammarahm-ed** [comment] 2023-02-13 10:39
> @ammarahm-ed I am not sure if the problem has been fixed. We have to call `hide` twice to close ActionSheet. Is anyone else experiencing this or is it a problem with our code?

Is the sheet nested/opened above another sheet? Or is it a simple sheet?

**Comment by pafry7** [comment] 2023-02-13 10:41
Yep, they have the same parent node:
```
    <ActionSheetLogout />
    <ActionSheetProfileRemoval />
```
Should we pass `context` here?

**Comment by ammarahm-ed** [comment] 2023-02-13 10:50
@pafry7 Can you try this and see what you get?

```js
import {getSheetStack} from "react-native-actions-sheet";
getSheetStack()
```

**Comment by ammarahm-ed** [comment] 2023-02-13 10:53
@pafry7 Also are you using `<SheetProvider/>` or not?

**Comment by pafry7** [comment] 2023-02-13 11:22
@ammarahm-ed Thank you for your time.
1. `getSheetStack` returns an empty array
2. The problem with double-clicking is gone. We forgot to import `sheets.tsx`. 
3. Now, we are not able to open any `ActionSheet` after closing it once.

`sheets.tsx` are imported in the same file as `SheetProvider` is used:
```
import { registerSheet } from "react-native-actions-sheet";
import {...} from "..."

registerSheet(LOGOUT_ACTION_ID, ActionSheetLogout);
registerSheet(PROFILE_REMOVAL_ACTION_ID, ActionSheetProfileRemoval);

export {};
```

ActionSheet:
```
export const LOGOUT_ACTION_ID = "logout";

const ActionSheetLogout = () => {
  return (
    <AppActionSheet
      id={LOGOUT_ACTION_ID}
    >
      <Button
        label="Close"
        onPress={() => {
          void SheetManager.hide(LOGOUT_ACTION_ID);
        }}
      />
    </AppActionSheet>
  );
};

export default ActionSheetLogout;
```
We are opening it in another component with `SheetManager.show(LOGOUT_ACTION_ID)`. Same code is working in v8.0.13.

**Comment by ammarahm-ed** [comment] 2023-02-13 11:29
@pafry7 Fixing this.

**Comment by ammarahm-ed** [comment] 2023-02-13 11:43
@pafry7 try 0.8.20

**Comment by pafry7** [comment] 2023-02-13 11:56
@ammarahm-ed seems to work, thanks. There is a new `console.log` to be removed. You could use linter for that: https://github.com/ammarahm-ed/react-native-actions-sheet/pull/268#issuecomment-1427690582

**Comment by ammarahm-ed** [comment] 2023-02-13 12:02
@pafry7 Can't find the new console.log in the code

**Comment by pafry7** [comment] 2023-02-13 12:07
In my console, I had the following logs:
 ```
 LOG ["global"] $$-auto-new-game-global-provider
 LOG  ["global"] $$-auto-logout-global-provider
 LOG  ["global"] $$-auto-profileRemoval-global-provider
 LOG  ["global"] $$-auto-logout-global-provider
 LOG  ["global"] $$-auto-profileRemoval-global-provider
 ```

**Comment by ammarahm-ed** [comment] 2023-02-13 14:25
@pafry7 Removed in 0.8.21

**Closed** 2023-02-13 14:32 UTC
